{% set name = "apache-airflow-providers-common-sql" %}
{% set version = "1.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_common_sql-{{ version }}.tar.gz
  sha256: 6179512edf261ede96adda31a535eec024471a5708a7528d27a4ece72f35783f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - apache-airflow >=2.7.0
    - more-itertools >=9.0.0
    - sqlparse >=0.4.2

test:
  imports:
    - airflow.providers.common.sql
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-common-sql for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/common/sql/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-common-sql/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
